openapi: 3.0.3
info:
  title: Activity Log Service API
  description: |
    A microservice for managing activity logs using gRPC and following Domain-Driven Design (DDD) principles.
    
    This API provides endpoints for creating, retrieving, and listing activity logs for companies.
    Activity logs track changes made to objects within a company's system, including the actor who made the change.
  version: 1.0.0
  contact:
    name: Activity Log Service Team
    email: support@activitylog.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:9000
    description: Local development server (gRPC)
  - url: http://localhost:8080
    description: Local development server (HTTP Gateway - if implemented)

paths:
  /activity-logs:
    post:
      summary: Create Activity Log
      description: Creates a new activity log entry for tracking changes in the system
      operationId: createActivityLog
      tags:
        - Activity Logs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActivityLogRequest'
            examples:
              user_creation:
                summary: User Creation Log
                value:
                  activity_name: "user_created"
                  company_id: "company_123"
                  object_name: "user"
                  object_id: "user_456"
                  changes: "{\"name\": \"John Doe\", \"email\": \"john.doe@example.com\", \"role\": \"admin\"}"
                  formatted_message: "User John Doe (john.doe@example.com) was created with admin role"
                  actor_id: "admin_789"
                  actor_name: "System Administrator"
                  actor_email: "admin@company123.com"
              user_update:
                summary: User Update Log
                value:
                  activity_name: "user_updated"
                  company_id: "company_123"
                  object_name: "user"
                  object_id: "user_456"
                  changes: "{\"email\": {\"old\": \"john.doe@example.com\", \"new\": \"john.smith@example.com\"}}"
                  formatted_message: "User email was updated from john.doe@example.com to john.smith@example.com"
                  actor_id: "admin_789"
                  actor_name: "System Administrator"
                  actor_email: "admin@company123.com"
      responses:
        '200':
          description: Activity log created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateActivityLogResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: List Activity Logs
      description: Retrieves a paginated list of activity logs for a specific company
      operationId: listActivityLogs
      tags:
        - Activity Logs
      parameters:
        - name: company_id
          in: query
          required: true
          description: Company ID to filter activity logs
          schema:
            type: string
            example: "company_123"
        - name: page
          in: query
          required: false
          description: Page number for pagination (default: 1)
          schema:
            type: integer
            minimum: 1
            default: 1
            example: 1
        - name: limit
          in: query
          required: false
          description: Number of items per page (default: 10, max: 100)
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
            example: 10
      responses:
        '200':
          description: List of activity logs retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListActivityLogsResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /activity-logs/{id}:
    get:
      summary: Get Activity Log
      description: Retrieves a specific activity log by its ID
      operationId: getActivityLog
      tags:
        - Activity Logs
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the activity log
          schema:
            type: string
            example: "550e8400e29b41d4a716446655440000"
      responses:
        '200':
          description: Activity log retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivityLogResponse'
        '404':
          description: Activity log not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Invalid activity log ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ActivityLog:
      type: object
      description: Activity log entity representing a tracked change in the system
      required:
        - id
        - activity_name
        - company_id
        - object_name
        - object_id
        - formatted_message
        - actor_id
        - actor_name
        - actor_email
        - created_at
      properties:
        id:
          type: string
          description: Unique identifier for the activity log
          example: "550e8400e29b41d4a716446655440000"
        activity_name:
          type: string
          description: Name/type of the activity performed
          example: "user_created"
        company_id:
          type: string
          description: ID of the company this activity belongs to
          example: "company_123"
        object_name:
          type: string
          description: Name of the object/entity that was changed
          example: "user"
        object_id:
          type: string
          description: ID of the specific object that was changed
          example: "user_456"
        changes:
          type: string
          description: JSON string containing the details of changes made
          example: "{\"name\": \"John Doe\", \"email\": \"john.doe@example.com\"}"
        formatted_message:
          type: string
          description: Human-readable message describing the activity
          example: "User John Doe (john.doe@example.com) was created with admin role"
        actor_id:
          type: string
          description: ID of the user/system that performed the activity
          example: "admin_789"
        actor_name:
          type: string
          description: Name of the actor who performed the activity
          example: "System Administrator"
        actor_email:
          type: string
          format: email
          description: Email address of the actor who performed the activity
          example: "admin@company123.com"
        created_at:
          type: string
          format: date-time
          description: Timestamp when the activity log was created
          example: "2023-12-07T10:30:00Z"

    CreateActivityLogRequest:
      type: object
      description: Request payload for creating a new activity log
      required:
        - activity_name
        - company_id
        - object_name
        - object_id
        - formatted_message
        - actor_id
        - actor_name
        - actor_email
      properties:
        activity_name:
          type: string
          description: Name/type of the activity performed
          example: "user_created"
          minLength: 1
          maxLength: 100
        company_id:
          type: string
          description: ID of the company this activity belongs to
          example: "company_123"
          minLength: 1
          maxLength: 50
        object_name:
          type: string
          description: Name of the object/entity that was changed
          example: "user"
          minLength: 1
          maxLength: 50
        object_id:
          type: string
          description: ID of the specific object that was changed
          example: "user_456"
          minLength: 1
          maxLength: 100
        changes:
          type: string
          description: JSON string containing the details of changes made
          example: "{\"name\": \"John Doe\", \"email\": \"john.doe@example.com\"}"
        formatted_message:
          type: string
          description: Human-readable message describing the activity
          example: "User John Doe (john.doe@example.com) was created with admin role"
          minLength: 1
          maxLength: 500
        actor_id:
          type: string
          description: ID of the user/system that performed the activity
          example: "admin_789"
          minLength: 1
          maxLength: 50
        actor_name:
          type: string
          description: Name of the actor who performed the activity
          example: "System Administrator"
          minLength: 1
          maxLength: 100
        actor_email:
          type: string
          format: email
          description: Email address of the actor who performed the activity
          example: "admin@company123.com"
          maxLength: 255

    CreateActivityLogResponse:
      type: object
      description: Response after successfully creating an activity log
      required:
        - activity_log
      properties:
        activity_log:
          $ref: '#/components/schemas/ActivityLog'

    GetActivityLogResponse:
      type: object
      description: Response containing a single activity log
      required:
        - activity_log
      properties:
        activity_log:
          $ref: '#/components/schemas/ActivityLog'

    ListActivityLogsResponse:
      type: object
      description: Response containing a paginated list of activity logs
      required:
        - activity_logs
        - total
        - page
        - limit
      properties:
        activity_logs:
          type: array
          description: Array of activity logs for the current page
          items:
            $ref: '#/components/schemas/ActivityLog'
        total:
          type: integer
          description: Total number of activity logs available
          example: 150
          minimum: 0
        page:
          type: integer
          description: Current page number
          example: 1
          minimum: 1
        limit:
          type: integer
          description: Number of items per page
          example: 10
          minimum: 1
          maximum: 100

    Error:
      type: object
      description: Error response structure
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: Error code
          example: 400
        message:
          type: string
          description: Error message
          example: "Invalid request parameters"
        details:
          type: string
          description: Additional error details
          example: "company_id is required"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

security:
  - BearerAuth: []

tags:
  - name: Activity Logs
    description: Operations related to activity log management

externalDocs:
  description: Activity Log Service Documentation
  url: https://github.com/your-org/activity-log-service